baseurl = "http://jamiedumont.co.uk/"
title = "Jamie Dumont"
metaDataFormat = "yaml"

relativeURLs = false
canonifyURLs = false

[params]
  description = "Jamie Dumont is a Full-Stack Developer and UX Designer who builds websites big and small and advises on how to build high performance websites to support your business."
  [params.social]
    github          = "jamiedumont"
    facebook        = "tacticallycreative"
    facebook_admin  = "jamiedumont0"  # This needs to be a page admin to get domain insights
    twitter         = "jamiedumont"
    twitter_domain  = "Jamie Dumont" # This domain shows in twitter cards as "View on `twitter_domain`"
    googleplus      = ""
    pinterest       = ""
    instagram       = ""
    youtube         = ""
    linkedin        = ""
  [params.authors]
    [params.authors.Jamie]
      name          = "Jamie Dumont"
      thumbnail     = ""
      images        = [
                        "",
                        "",
                      ]
      bio           = "Jamie is the founder of Tactically Creative. He set out to change how small businesses could build websites."
      email         = "jamie@tactically-creative.co.uk"

      [params.authors.Jamie.social]
        facebook = "jamiedumont0"

