name = "Tacticallycreative"
license = "MIT"
licenselink = "https://github.com/.../.../LICENSE.md"
description = "Theme for Tactically Creative's own website"
homepage = "http://tactically-creative.co.uk/"
tags = ["", ""]
features = ["", ""]

[author]
  name = "Jamie Dumont"
  homepage = "http://tactically-creative.co.uk/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
